load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "additionalinitialisms",
    srcs = [
        "gen.go",
        "generate.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/output-options/additionalinitialisms",
    visibility = ["//visibility:public"],
)
