load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "gorilla",
    srcs = ["server.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/internal/test/parameters/roundtrip/gorilla",
    visibility = ["//:__subpackages__"],
    deps = ["//internal/test/parameters/roundtrip/gorilla/gen"],
)
