load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "fiber_lib",
    srcs = ["petstore.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/petstore-expanded/fiber",
    visibility = ["//visibility:private"],
    deps = ["//examples/petstore-expanded/fiber/server"],
)

go_binary(
    name = "fiber",
    embed = [":fiber_lib"],
    visibility = ["//visibility:public"],
)
