load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "overlay_lib",
    srcs = ["main.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/overlay",
    visibility = ["//visibility:private"],
    deps = [
        "//examples/overlay/api",
        "@com_github_gorilla_mux//:mux",
    ],
)

go_binary(
    name = "overlay",
    embed = [":overlay_lib"],
    visibility = ["//visibility:public"],
)
