load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "echo",
    srcs = ["server.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/internal/test/parameters/roundtrip/echo",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/test/parameters/roundtrip/echo/gen",
        "@com_github_labstack_echo_v4//:echo",
    ],
)
