load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "codegen",
    srcs = [
        "codegen.go",
        "configuration.go",
        "extension.go",
        "externalref.go",
        "filter.go",
        "gather.go",
        "inline.go",
        "merge_schemas.go",
        "merge_schemas_v1.go",
        "minimum_go_version.go",
        "operations.go",
        "prune.go",
        "resolve_names.go",
        "schema.go",
        "server_urls.go",
        "template_helpers.go",
        "typemapping.go",
        "utils.go",
        "validate_spec.go",
    ],
    embedsrcs = [
        "templates/additional-properties.tmpl",
        "templates/callback-initiator.tmpl",
        "templates/chi/chi-handler.tmpl",
        "templates/chi/chi-interface.tmpl",
        "templates/chi/chi-middleware.tmpl",
        "templates/chi/chi-receiver.tmpl",
        "templates/client-with-responses.tmpl",
        "templates/client.tmpl",
        "templates/constants.tmpl",
        "templates/echo/echo-interface.tmpl",
        "templates/echo/echo-receiver.tmpl",
        "templates/echo/echo-register.tmpl",
        "templates/echo/echo-wrappers.tmpl",
        "templates/echo/v5/echo-interface.tmpl",
        "templates/echo/v5/echo-receiver.tmpl",
        "templates/echo/v5/echo-register.tmpl",
        "templates/echo/v5/echo-wrappers.tmpl",
        "templates/fiber-v3/fiber-handler.tmpl",
        "templates/fiber-v3/fiber-interface.tmpl",
        "templates/fiber-v3/fiber-middleware.tmpl",
        "templates/fiber-v3/fiber-receiver.tmpl",
        "templates/fiber/fiber-handler.tmpl",
        "templates/fiber/fiber-interface.tmpl",
        "templates/fiber/fiber-middleware.tmpl",
        "templates/fiber/fiber-receiver.tmpl",
        "templates/gin/gin-interface.tmpl",
        "templates/gin/gin-receiver.tmpl",
        "templates/gin/gin-register.tmpl",
        "templates/gin/gin-wrappers.tmpl",
        "templates/gorilla/gorilla-interface.tmpl",
        "templates/gorilla/gorilla-middleware.tmpl",
        "templates/gorilla/gorilla-receiver.tmpl",
        "templates/gorilla/gorilla-register.tmpl",
        "templates/imports.tmpl",
        "templates/inline.tmpl",
        "templates/iris/iris-handler.tmpl",
        "templates/iris/iris-interface.tmpl",
        "templates/iris/iris-middleware.tmpl",
        "templates/iris/iris-receiver.tmpl",
        "templates/param-types.tmpl",
        "templates/request-bodies.tmpl",
        "templates/server-urls.tmpl",
        "templates/stdhttp/std-http-handler.tmpl",
        "templates/stdhttp/std-http-interface.tmpl",
        "templates/stdhttp/std-http-middleware.tmpl",
        "templates/stdhttp/std-http-receiver.tmpl",
        "templates/strict/strict-echo.tmpl",
        "templates/strict/strict-echo5.tmpl",
        "templates/strict/strict-fiber-interface.tmpl",
        "templates/strict/strict-fiber-v3-interface.tmpl",
        "templates/strict/strict-fiber-v3.tmpl",
        "templates/strict/strict-fiber.tmpl",
        "templates/strict/strict-gin.tmpl",
        "templates/strict/strict-http.tmpl",
        "templates/strict/strict-interface.tmpl",
        "templates/strict/strict-iris-interface.tmpl",
        "templates/strict/strict-iris.tmpl",
        "templates/strict/strict-responses.tmpl",
        "templates/typedef.tmpl",
        "templates/union-and-additional-properties.tmpl",
        "templates/union.tmpl",
        "templates/webhook-initiator.tmpl",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/util",
        "@com_github_getkin_kin_openapi//openapi3",
        "@org_golang_x_mod//modfile",
        "@org_golang_x_text//cases",
        "@org_golang_x_text//language",
        "@org_golang_x_tools//imports",
    ],
)

go_test(
    name = "codegen_test",
    srcs = [
        "codegen_test.go",
        "configuration_test.go",
        "extension_test.go",
        "filter_test.go",
        "gather_test.go",
        "merge_schemas_test.go",
        "operations_spec_order_test.go",
        "operations_test.go",
        "prune_test.go",
        "resolve_names_test.go",
        "schema_test.go",
        "server_urls_test.go",
        "typemapping_test.go",
        "utils_test.go",
    ],
    data = [":test_schema"],
    embed = [":codegen"],
    embedsrcs = ["test_spec.yaml"],
    deps = [
        "//pkg/util",
        "@com_github_getkin_kin_openapi//openapi3",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)

filegroup(
    name = "test_schema",
    srcs = glob(["test_specs/*.yaml"]) + ["test_schema.json"],
)
