load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "stdhttp_lib",
    srcs = ["petstore.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/petstore-expanded/stdhttp",
    visibility = ["//visibility:private"],
    deps = ["//examples/petstore-expanded/stdhttp/server"],
)

go_binary(
    name = "stdhttp",
    embed = [":stdhttp_lib"],
    visibility = ["//visibility:public"],
)
