load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "multipackage",
    srcs = [
        "doc.go",
        "externalref.gen.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/internal/test/references/multipackage",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/test/references/multipackage/packageA",
        "//internal/test/references/multipackage/packageB",
        "//internal/test/references/multipackage/petstore",
        "@com_github_getkin_kin_openapi//openapi3",
    ],
)

go_test(
    name = "multipackage_test",
    srcs = ["imports_test.go"],
    embed = [":multipackage"],
    deps = [
        "//internal/test/references/multipackage/packageA",
        "//internal/test/references/multipackage/packageB",
        "//internal/test/references/multipackage/petstore",
        "@com_github_stretchr_testify//require",
    ],
)
