load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gorillamux_lib",
    srcs = ["main.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/minimal-server/gorillamux",
    visibility = ["//visibility:private"],
    deps = [
        "//examples/minimal-server/gorillamux/api",
        "@com_github_gorilla_mux//:mux",
    ],
)

go_binary(
    name = "gorillamux",
    embed = [":gorillamux_lib"],
    visibility = ["//visibility:public"],
)
