load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "discriminated_union_allof",
    srcs = ["doc.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/internal/test/references/multipackage/discriminated_union_allof",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "discriminated_union_allof_test",
    srcs = ["issue_test.go"],
    embed = [":discriminated_union_allof"],
    deps = [
        "//internal/test/references/multipackage/discriminated_union_allof/gen/api",
        "//internal/test/references/multipackage/discriminated_union_allof/gen/common",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
