load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "fiberv3_lib",
    srcs = ["petstore.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/petstore-expanded/fiberv3",
    visibility = ["//visibility:private"],
    deps = [
        "//examples/petstore-expanded/fiberv3/api",
        "@com_github_gofiber_fiber_v3//:fiber",
        "@com_github_oapi_codegen_fiber_v3_middleware//:fiber-v3-middleware",
    ],
)

go_binary(
    name = "fiberv3",
    embed = [":fiberv3_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "fiberv3_test",
    srcs = ["petstore_test.go"],
    embed = [":fiberv3_lib"],
    deps = [
        "//examples/petstore-expanded/fiberv3/api",
        "@com_github_gofiber_fiber_v3//:fiber",
        "@com_github_stretchr_testify//assert",
    ],
)
