load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "spec_validation_test",
    srcs = ["spec_validation_test.go"],
    data = glob(["testdata/**"]),
    deps = [
        "//pkg/codegen",
        "//pkg/util",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
