load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fiber",
    srcs = [
        "doc.go",
        "fiber.gen.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/internal/test/bodies/content_types/text_non_string/fiber",
    visibility = ["//:__subpackages__"],
    deps = ["@com_github_gofiber_fiber_v2//:fiber"],
)

go_test(
    name = "fiber_test",
    srcs = ["fiber_test.go"],
    embed = [":fiber"],
    deps = [
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_gofiber_fiber_v2//middleware/adaptor",
        "@com_github_oapi_codegen_testutil//:testutil",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
