load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "server",
    srcs = [
        "server.go",
        "setup.go",
        "store.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/petstore-expanded/echo/server",
    visibility = ["//visibility:public"],
    deps = [
        "//examples/petstore-expanded/echo/api",
        "@com_github_labstack_echo_v4//:echo",
        "@com_github_oapi_codegen_echo_middleware//:echo-middleware",
    ],
)
