load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "basic",
    srcs = [
        "basic.gen.go",
        "doc.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/internal/test/servers/routers/basic",
    visibility = ["//:__subpackages__"],
    deps = [
        "@com_github_go_chi_chi_v5//:chi",
        "@com_github_oapi_codegen_runtime//:runtime",
        "@com_github_oapi_codegen_runtime//types",
    ],
)

go_test(
    name = "basic_test",
    srcs = ["server_test.go"],
    embed = [":basic"],
    deps = ["@com_github_stretchr_testify//assert"],
)
