load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "server_lib",
    srcs = ["main.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/callback/server",
    visibility = ["//visibility:private"],
    deps = [
        "//examples/callback",
        "@com_github_google_uuid//:uuid",
    ],
)

go_binary(
    name = "server",
    embed = [":server_lib"],
    visibility = ["//visibility:public"],
)
