load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "testclient",
    srcs = ["testclient.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/petstore-expanded/common/client/testclient",
    visibility = ["//visibility:public"],
    deps = ["//examples/petstore-expanded/common/client/openapi"],
)
