load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "echo_lib",
    srcs = ["main.go"],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/authenticated-api/echo",
    visibility = ["//visibility:private"],
    deps = [
        "//examples/authenticated-api/echo/api",
        "//examples/authenticated-api/echo/server",
        "@com_github_labstack_echo_v4//:echo",
    ],
)

go_binary(
    name = "echo",
    embed = [":echo_lib"],
    visibility = ["//visibility:public"],
)
