load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "iris",
    srcs = [
        "doc.go",
        "iris.gen.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/internal/test/bodies/content_types/text_non_string/iris",
    visibility = ["//:__subpackages__"],
    deps = ["@com_github_kataras_iris_v12//:iris"],
)

go_test(
    name = "iris_test",
    srcs = ["iris_test.go"],
    embed = [":iris"],
    deps = [
        "@com_github_kataras_iris_v12//:iris",
        "@com_github_oapi_codegen_testutil//:testutil",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
