load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "serverurls",
    srcs = [
        "gen.go",
        "generate.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/generate/serverurls",
    visibility = ["//visibility:public"],
)

go_test(
    name = "serverurls_test",
    srcs = ["gen_test.go"],
    embed = [":serverurls"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
