load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "sse",
    srcs = [
        "generate.go",
        "impl.go",
        "streaming.gen.go",
    ],
    importpath = "github.com/oapi-codegen/oapi-codegen/v2/examples/streaming/stdhttp/sse",
    visibility = ["//visibility:public"],
    deps = ["@com_github_getkin_kin_openapi//openapi3"],
)
